# Generated by Django 2.1.7 on 2019-03-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_suggestion_suggestion_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion_count',
        ),
    ]
